### PR TITLE
Add support for RTemplate embedding/sourcing

### PR DESCRIPTION
**Pull request by mdzik**
This commit ads a tag
```
<?RT path/to/file/wrt/compiler.RT ?>
```
which sources/e,beds files and allows for reuse of RT code

Example:

outer.RT
```
<?R a = 5 ?>
<?RT inner.RT ?>
<?R print(b) ?>
```

inner.RT
```
<?R 
print(a) 
b = 11
?>
```

 RTfile('tests/outer.RT') results in 
```
 [1] "# RTemplate genereted code."                                                                      
[33] "############# Code from Rt file ############"                                                     
[34] ""                                                                                                 
[35] " a = 5 "                                                                                          
[36] "cat( \"\\n\" );"                                                                                  
[37] "cat( \"\" );"                                                                                     
[38] "# RTemplate genereted code."                                                                      
[39] "############# RT standard functions ########"                                                     
[70] "############# Code from Rt file ############"                                                     
[71] ""                                                                                                 
[72] " "                                                                                                
[73] "print(a) "                                                                                        
[74] "b = 11"                                                                                           
[75] ""                                                                                                 
[76] "cat(\"\\n\")"                                                                                     
[77] "cat( \"\\n\" );"                                                                                  
[78] "cat( \"\" );"                                                                                     
[79] " print(b) "                                                                                       
[80] "cat(\"\\n\")"    
```

### CODE REVIEW

**Review by llaniewski — CHANGES_REQUESTED** [review]
I like the idea, but I think the current implementation duplicates the header code. Also some options from the RTconvert, should be passed to the included rtemplate parsing (like `mark.lines`)

**Comment by mdzik** [comment]
Good point - gimme 5 ;)

**Comment by mdzik** [comment]
I think that is working as expected now. I'm not certain about linemark

```
> load_all('.'); RTfile('./tests/upper.RT', c(), TRUE)
ℹ Loading rtemplate
 [1] "# RTemplate genereted code."                                                                      
 [2] "############# RT standard functions ########"                                                     
 [3] ""                                                                                                 
 [4] "printf = function(...) {"                                                                         
 [5] "  cat(sprintf(...))"                                                                              
 [6] "}"                                                                                                
 [7] "quiet.source = function(..., comment=\"# \") {"                                                   
 [8] "  f=textConnection(\"quiet.source.text\",\"w\");"                                                 
 [9] "  sink(f); ret=source(...); sink();"                                                              
[10] "  close(f);"                                                                                      
[11] "  cat(paste(comment,quiet.source.text,\"\n\",sep=\"\"),sep=\"\")"                                 
[12] "  ret"                                                                                            
[13] "}"                                                                                                
[14] "if (!exists(\"include.dir\")) include.dir=NULL;"                                                  
[15] "source = function(file,...) {"                                                                    
[16] "  pot = c(file, paste(include.dir,file,sep=\"/\"))"                                               
[17] "  sel = sapply(pot,file.exists)"                                                                  
[18] "  sel = which(sel)"                                                                               
[19] "  if (length(sel) < 1)"                                                                           
[20] "    stop(\"file not found:\",file,\" in include directories:\",paste(include.dir,collapse=\",\"))"
[21] "  newfile=pot[sel[1]]"                                                                            
[22] "  base::source(file=newfile,...)"                                                                 
[23] "}"                                                                                                
[24] "add.include.dir = function(dir) {"                                                                
[25] "  if (substr(dir,1,1) != \"/\") dir = paste(getwd(),dir,sep=\"/\");"                              
[26] "  include.dir <<- c(include.dir,dir)"                                                             
[27] "}"                                                                                                
[28] "linemark=function(...) {invisible(NULL)}"                                                         
[29] ""                                                                                                 
[30] "############# Parameters and settings ######"                                                     
[31] ""                                                                                                 
[32] ""                                                                                                 
[33] "############# Code from Rt file ############"                                                     
[34] ""                                                                                                 
[35] "linemark(1,\"./tests/upper.RT\",reset=FALSE)"                                                     
[36] " a = 5 "                                                                                          
[37] "linemark(1,\"./tests/upper.RT\",reset=FALSE)"                                                     
[38] "cat( \"\\n\" );"                                                                                  
[39] "linemark(2,\"./tests/upper.RT\",reset=FALSE)"                                                     
[40] "cat( \"\" );"                                                                                     
[41] "# RTemplate included file"                                                                        
[42] "# Filename:   ./tests/inner.RT"                                                                   
[43] "linemark(1,\"./tests/inner.RT\",reset=FALSE)"                                                     
[44] "linemark(1,\"./tests/inner.RT\",reset=TRUE)"                                                      
[45] " "                                                                                                
[46] "print(a) "                                                                                        
[47] "b = 11"                                                                                           
[48] ""                                                                                                 
[49] "cat(\"\\n\")"                                                                                     
[50] "#END included for filename:   ./tests/inner.RT"                                                   
[51] "linemark(-1,\"./tests/inner.RT\",reset=FALSE)"                                                    
[52] "linemark(2,\"./tests/upper.RT\",reset=FALSE)"                                                     
[53] "cat( \"\\n\" );"                                                                                  
[54] "linemark(3,\"./tests/upper.RT\",reset=FALSE)"                                                     
[55] "cat( \"\" );"                                                                                     
[56] " print(b) "                                                                                       
[57] "cat(\"\\n\")"                                                                                     
[58] "linemark(-1,\"./tests/upper.RT\",reset=FALSE)"       
```

**Comment by ggruszczynski** [comment]
@llaniewski up

**Review by llaniewski — APPROVED** [review]

**Pull request merged**
